import { Product, Category, NavItem } from "@/types";

export const NAV_ITEMS: NavItem[] = [
  { label: "Home", href: "/" },
  { label: "Menu", href: "/menu" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

export const CATEGORIES: Category[] = [
  { id: "drinks", label: "Drinks", icon: "☕" },
  { id: "donuts", label: "Donuts", icon: "🍩" },
  { id: "snacks", label: "Snacks", icon: "🥐" },
];

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Espresso",
    price: 3.99,
    category: "drinks",
    description: "Rich, bold espresso shot with a perfect crema on top.",
    image: "/images/espresso.svg",
    color: "#FF6B2C",
    bgColor: "linear-gradient(135deg, #FF6B2C, #FF8C55)",
    rating: 4.8,
    isPopular: true,
    prepTime: "2 min",
  },
  {
    id: "2",
    name: "Latte",
    price: 4.5,
    category: "drinks",
    description: "Smooth espresso with perfectly steamed milk.",
    image: "/images/latte.svg",
    color: "#9C27B0",
    bgColor: "linear-gradient(135deg, #9C27B0, #CE93D8)",
    rating: 4.7,
    isPopular: true,
    prepTime: "4 min",
  },
  {
    id: "3",
    name: "Flat White",
    price: 4.25,
    category: "drinks",
    description: "Velvety microfoam with double ristretto espresso.",
    image: "/images/flatwhite.svg",
    color: "#FF6B2C",
    bgColor: "linear-gradient(135deg, #FF8C55, #FFD700)",
    rating: 4.9,
    isPopular: true,
    prepTime: "3 min",
  },
  {
    id: "4",
    name: "Cappuccino",
    price: 4.0,
    category: "drinks",
    description: "Classic Italian coffee with equal parts espresso, milk, and foam.",
    image: "/images/cappuccino.svg",
    color: "#4CAF50",
    bgColor: "linear-gradient(135deg, #4CAF50, #81C784)",
    rating: 4.6,
    prepTime: "4 min",
  },
  {
    id: "5",
    name: "Pink in Disguise",
    price: 3.55,
    category: "donuts",
    description: "Fluffy pink glazed donut with sprinkles.",
    image: "/images/donut-pink.svg",
    color: "#FF69B4",
    bgColor: "linear-gradient(135deg, #FF69B4, #FFB6C1)",
    rating: 4.5,
    prepTime: "Ready",
  },
  {
    id: "6",
    name: "Baked Blueberry",
    price: 3.55,
    category: "donuts",
    description: "Dark chocolate glazed donut with rich cocoa flavor.",
    image: "/images/donut-chocolate.svg",
    color: "#5D4037",
    bgColor: "linear-gradient(135deg, #5D4037, #8D6E63)",
    rating: 4.4,
    prepTime: "Ready",
  },
  {
    id: "7",
    name: "Glaze Party",
    price: 3.55,
    category: "donuts",
    description: "Classic glazed donut with a perfect golden finish.",
    image: "/images/donut-glazed.svg",
    color: "#FFD700",
    bgColor: "linear-gradient(135deg, #FFD700, #FFF176)",
    rating: 4.6,
    prepTime: "Ready",
  },
  {
    id: "8",
    name: "Croissant",
    price: 2.99,
    category: "snacks",
    description: "Buttery, flaky French croissant baked fresh daily.",
    image: "/images/croissant.svg",
    color: "#FF8C00",
    bgColor: "linear-gradient(135deg, #FF8C00, #FFD700)",
    rating: 4.7,
    prepTime: "Ready",
  },
];

export const HERO_STATS = [
  { value: "500+", label: "Menu Items" },
  { value: "10K+", label: "Happy Customers" },
  { value: "4.9★", label: "App Rating" },
];
